# Generated by Django 5.1.5 on 2025-02-03 05:21

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "question",
                    models.TextField(
                        help_text="Enter the question",
                        max_length=255,
                        verbose_name="Question",
                    ),
                ),
                (
                    "answer",
                    tinymce.models.HTMLField(
                        help_text="Enter the answer", verbose_name="Answer"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("es", "Spanish"),
                            ("fr", "French"),
                            ("de", "German"),
                            ("it", "Italian"),
                            ("pt", "Portuguese"),
                            ("nl", "Dutch"),
                            ("ru", "Russian"),
                            ("ja", "Japanese"),
                            ("ko", "Korean"),
                            ("zh", "Chinese"),
                            ("ar", "Arabic"),
                            ("hi", "Hindi"),
                            ("bn", "Bengali"),
                            ("pa", "Punjabi"),
                            ("ur", "Urdu"),
                            ("tr", "Turkish"),
                            ("vi", "Vietnamese"),
                            ("th", "Thai"),
                            ("id", "Indonesian"),
                            ("tl", "Filipino"),
                            ("ms", "Malay"),
                            ("sw", "Swahili"),
                            ("yo", "Yoruba"),
                            ("ig", "Igbo"),
                            ("ha", "Hausa"),
                            ("am", "Amharic"),
                            ("so", "Somali"),
                            ("zu", "Zulu"),
                            ("xh", "Xhosa"),
                            ("af", "Afrikaans"),
                            ("st", "Sesotho"),
                        ],
                        help_text="Choices include:\n- 'en': English\n- 'es': Spanish\n- 'fr': French\n- 'de': German\n- 'it': Italian\n- 'pt': Portuguese\n- 'nl': Dutch\n- 'ru': Russian\n- 'ja': Japanese\n- 'ko': Korean\n- 'zh': Chinese\n- 'ar': Arabic\n- 'hi': Hindi\n- 'bn': Bengali\n- 'pa': Punjabi\n- 'ur': Urdu\n- 'tr': Turkish\n- 'vi': Vietnamese\n- 'th': Thai\n- 'id': Indonesian\n- 'tl': Filipino\n- 'ms': Malay\n- 'sw': Swahili\n- 'yo': Yoruba\n- 'ig': Igbo\n- 'ha': Hausa\n- 'am': Amharic\n- 'so': Somali\n- 'zu': Zulu\n- 'xh': Xhosa\n- 'af': Afrikaans\n- 'st': Sesotho",
                        max_length=2,
                        verbose_name="Language",
                    ),
                ),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
            },
        ),
    ]
