# Generated by Django 5.1.5 on 2025-02-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faq", "0004_alter_faq_translations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faq",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("mr", "Marathi"),
                    ("hi", "Hindi"),
                    ("ta", "Tamil"),
                    ("bn", "Bengali"),
                    ("kn", "Kannada"),
                    ("gu", "Gujarati"),
                ],
                default="en",
                help_text="Choices include:\n- 'en': English\n- 'mr': Marathi\n- 'hi': Hindi\n- 'ta': Tamil\n- 'bn': Bengali\n- 'kn': Kannada\n- 'gu': Gujarati",
                max_length=2,
                verbose_name="Language",
            ),
        ),
    ]
